"""Lazy local download payloads: file:// pages cannot fetch sibling HTML files."""

import base64
import json

from .catalog import ROOT


def write_download_payloads(tools):
    folder = ROOT / "assets" / "downloads"
    folder.mkdir(exist_ok=True)
    for tool in tools:
        if tool.is_directory:
            continue
        encoded = base64.b64encode((ROOT / tool.path).read_bytes()).decode("ascii")
        payload = ("/* Generated by build.py; loaded only for local-file downloads. */\n"
                   "window.NHLocalDownloads = window.NHLocalDownloads || Object.create(null);\n"
                   f"window.NHLocalDownloads[{json.dumps(tool.id, ensure_ascii=False)}] = {json.dumps(encoded)};\n")
        (folder / f"{tool.id}.js").write_text(payload, encoding="utf-8", newline="\n")
